[debug] [2022-07-04T20:30:59.051Z] ----------------------------------------------------------------------
[debug] [2022-07-04T20:30:59.053Z] Command:       /home/fabiochiquezi/.nvm/versions/node/v16.15.0/bin/node /home/fabiochiquezi/.nvm/versions/node/v16.15.0/bin/firebase emulators:start
[debug] [2022-07-04T20:30:59.053Z] CLI Version:   11.1.0
[debug] [2022-07-04T20:30:59.053Z] Platform:      linux
[debug] [2022-07-04T20:30:59.054Z] Node Version:  v16.15.0
[debug] [2022-07-04T20:30:59.054Z] Time:          Mon Jul 04 2022 17:30:59 GMT-0300 (Brasilia Standard Time)
[debug] [2022-07-04T20:30:59.054Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-07-04T20:30:59.105Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-07-04T20:30:59.106Z] > authorizing via signed-in user (fabiochiquezi@gmail.com)
[info] i  emulators: Starting emulators: auth {"metadata":{"emulator":{"name":"hub"},"message":"Starting emulators: auth"}}
[debug] [2022-07-04T20:30:59.153Z] [hub] writing locator at /tmp/hub-toolnextjsboilerplate.json
[debug] [2022-07-04T20:31:09.183Z] Ignoring unsupported arg: auto_download {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: auto_download"}}
[debug] [2022-07-04T20:31:09.183Z] Ignoring unsupported arg: port {"metadata":{"emulator":{"name":"ui"},"message":"Ignoring unsupported arg: port"}}
[debug] [2022-07-04T20:31:09.183Z] Starting Emulator UI with command {"binary":"node","args":["--dns-result-order=ipv4first","/home/fabiochiquezi/.cache/firebase/emulators/ui-v1.7.0/server.bundle.js"],"optionalArgs":[],"joinArgs":false} {"metadata":{"emulator":{"name":"ui"},"message":"Starting Emulator UI with command {\"binary\":\"node\",\"args\":[\"--dns-result-order=ipv4first\",\"/home/fabiochiquezi/.cache/firebase/emulators/ui-v1.7.0/server.bundle.js\"],\"optionalArgs\":[],\"joinArgs\":false}"}}
[info] i  ui: Emulator UI logging to ui-debug.log {"metadata":{"emulator":{"name":"ui"},"message":"Emulator UI logging to \u001b[1mui-debug.log\u001b[22m"}}
[debug] [2022-07-04T20:31:09.339Z] Web / API server started at localhost:4040
 {"metadata":{"emulator":{"name":"ui"},"message":"Web / API server started at localhost:4040\n"}}
[info] 
┌─────────────────────────────────────────────────────────────┐
│ ✔  All emulators ready! It is now safe to connect your app. │
│ i  View Emulator UI at http://localhost:4040                │
└─────────────────────────────────────────────────────────────┘

┌────────────────┬────────────────┬────────────────────────────┐
│ Emulator       │ Host:Port      │ View in Emulator UI        │
├────────────────┼────────────────┼────────────────────────────┤
│ Authentication │ localhost:9099 │ http://localhost:4040/auth │
└────────────────┴────────────────┴────────────────────────────┘
  Emulator Hub running at localhost:4400
  Other reserved ports: 4500

Issues? Report them at https://github.com/firebase/firebase-tools/issues and attach the *-debug.log files.
 
[warn] ⚠  Error: Internal state invariant broken: no user with ID: x7GQ22IdeSA9rK2BgWvK367aDdgk
    at AgentProjectState.getUserByLocalIdAssertingExists (/home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/emulator/auth/state.js:208:19)
    at AgentProjectState.validateRefreshToken (/home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/emulator/auth/state.js:295:24)
    at grantToken (/home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/emulator/auth/operations.js:1199:38)
    at Proxy.<anonymous> (/home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/emulator/auth/server.js:375:20)
    at /home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/node_modules/promise-breaker/index.js:265:46
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"metadata":{"emulator":{"name":"auth"},"message":"Error: Internal state invariant broken: no user with ID: x7GQ22IdeSA9rK2BgWvK367aDdgk\n    at AgentProjectState.getUserByLocalIdAssertingExists (/home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/emulator/auth/state.js:208:19)\n    at AgentProjectState.validateRefreshToken (/home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/emulator/auth/state.js:295:24)\n    at grantToken (/home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/emulator/auth/operations.js:1199:38)\n    at Proxy.<anonymous> (/home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/lib/emulator/auth/server.js:375:20)\n    at /home/fabiochiquezi/.nvm/versions/node/v16.15.0/lib/node_modules/firebase-tools/node_modules/promise-breaker/index.js:265:46\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}
